server:
  port: 8088

spring:
  messages:
    basename: messages
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**

  devtools:
    livereload:
      enabled: true

  h2:
    console:
      enabled: true
  jpa:
    show-sql: true